load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

# Header-only testing framework: lest.hpp
cc_library(
    name = "lest",
    hdrs = ["lest.hpp"],
    visibility = ["//visibility:public"],
)
