load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "merge_sorted_arrays",
    srcs = ["merge_sorted_arrays.cpp"],
    deps = ["//lib/lest"],
    copts = ["-Ilib/lest"],
)

cc_binary(
    name = "string_reverse",
    srcs = ["string_reverse.cpp"],
    deps = ["//lib/lest"],
    copts = ["-Ilib/lest"],
)

cc_binary(
    name = "words_reverse",
    srcs = ["words_reverse.cpp"],
    deps = ["//lib/lest"],
    copts = ["-Ilib/lest"],
)
